### ISSUE TITLE
Сценарии для ситуаций

### ISSUE THREAD

**Issue by ZhenyaBarsamov** [MKRTeam/KeyboardSmasher#6]
Нам нужны сценарий для игровых ситуаций

**Comment by ZhenyaBarsamov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) СРЕДНЕ ВАЖНО Сценарии для ситуаций (3 шт.)](https://trello.com/c/YjfPmSLb/5-1-%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B5-%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D0%B4%D0%BB%D1%8F-%D1%81%D0%B8%D1%82%D1%83%D0%B0%D1%86%D0%B8%D0%B9-3-%D1%88%D1%82)

**Comment by ZhenyaBarsamov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) МАЛО ВАЖНО Дописать сценарии ситуаций (еще 3 шт.)](https://trello.com/c/1JrRpRy8/8-2-%D0%BC%D0%B0%D0%BB%D0%BE-%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE-%D0%B4%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8-%D1%81%D0%B8%D1%82%D1%83%D0%B0%D1%86%D0%B8%D0%B9-%D0%B5%D1%89%D0%B5-3-%D1%88%D1%82)

**Comment by GraphFistaha** [comment]
> (1) СРЕДНЕ ВАЖНО Сценарии для ситуаций (3 шт.)

Это реализовано.
